# Generated by Django 3.0.14 on 2021-07-14 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210714_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='products',
        ),
    ]
